### ISSUE TITLE
Réduction de la portée de la notion d'organisation

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-service-public#2370]
L'échange ci-dessous du 19 février issu du forum nous amène à penser que la notion de cloisonnement par organisation n'est pas forcément très pratique quant à la recherche de RDV.

> Pour le CD92, aujourd'hui pour l'activité PMI/CPEF, pour l'accueil téléphonique des usagers, un seul canal : un numéro unique.
> 
> Derrière ce numéro unique, des chargés d'appels qui suivent un process pour tout le CD92 (les centres Départementaux PMI et CPEF) pour planifier des RDV avec les usagers sur le type de RDV concerné. L'outil du moment, c'est notre CRM, qui permet une recherche centre par centre (lieu) ou par Intervenant.
> 
> Demain, pour RDV-Solidarités, nous envisageons bien entendu d'ouvrir des droits de type secrétariat à ces chargés d'appels, pour nos 13 territoires, soit 13 organisations. Ces professionnels ne sont pas intervenants de RDV. Ils n'ont pas d'enjeu concernant leur planning.
> Par contre, là où il est important d'envisager au mieux l'utilisation, c'est lorsqu'une recherche de RDV est effectuée, et pas nécessairement attachée à une organisation ciblée.
> Par exemple, nous avons défini des plages d'ouverture (sur le CRM) pour de la vaccination BCG (sujet fort porteur pour les familles). Les chargés d'appel recherchent d'abord sur le site identifié comme étant le plus proche du lieu de résidence de la famille (selon la déclaration d'adresse). A défaut de trouver des résultats, élargissent en tentant la recherche sur d'autres site (une recherche par site, à renouveler, jusqu'à obtention d'un résultat - donc pas super satisfaisant).
> 
> Idéalement, nos chargés d'appels devraient pouvoir rechercher des RDV, comme le ferait un usager sur son interface (à partir d'une adresse, puis un service, puis un motif).
> 
> Sinon, dans la connaissance que j'ai de RDV-Solidarités aujourd'hui, notre chargé d'appel devra d'abord choisir l'organisation correspondant au lieu d'habitation de la famille, lancer sa recherche (tout va bien si on trouve quelque chose :grin:). Là où ça se corse, c'est lorsqu'il faut chercher ailleurs, sans cible particulière. Il faudrait alors ouvrir RDV-Solidarités sur un autre navigateur (pour ne pas être connecté en tant qu'agent), lancer la recherche hors connexion, avec les critères adresse, service, motif, afin de repérer les dispos les plus proches proposées, et ensuite lancer la recherche depuis le compte agent, sur l'organisation repérée comme étant porteuse de dispo. Bref, pas très ergonomique tout ça.
> 
> Ai-je bien perçu les contraintes et limites dans ce type de contexte d'usage ?
> 
> Peut-être qu'une notion de département, dans le périmètre du compte utilisateur, permettrait de dépasser ces contraintes ?

-- Clarisse (92)

**Comment by yaf** [comment]
Merci pour ce message.

J'ai l'impression que la meilleure solution serait de passer par l'interface usager effectivement. Pourquoi ne pas l'utiliser ?

> utiliser l'interface usager, reviendrait à créer un compte à la place de l'usager, et ça ne me parait pas souhaitable en terme de responsabilité (est-ce bien RGPD... ?). Il faudrait que le chargé d'appels créé le compte de l'usager, avec courriel et mot de passe. Si l'usager fait une seconde demande, il devra se souvenir de son mot de passe et le communiquer au chargé d'appel pour que la prise de RDV puisse aboutir... :smirk:
> De plus, la plateforme téléphonique informera les personnes de la possibilité de prendre RDV en ligne : ceux qui en ont la possibilité, qui le souhaitent, pourront faire la démarche de manière autonome.

-- Clarisse (92)

**Comment by yaf** [comment]
J'imagine que nous pourrions envisager que les agents, connecté avec leur compte, puissent naviguer sur l'interface dit « usager ». Se pose la question de la sélection de l'usager par contre.

Il y a déjà un chemin similaire via la recherche de créneau (bouton en haut à droite sur la page agenda ou sur la fiche usager). Par contre, cette option ne fonctionne pas pour le multi-organisation.

Peut-être que nous pourrions avoir un « bouton » depuis la fiche usager pour « prendre un rendez-vous » comme si nous étions connecté en tant que cet usager.

@AdrienDiPasquale  est-ce que ça serait envisageable ? J'ai un doute sur les impacts lié à la gestion de compte.

Peut-être que nous pourrions aussi « ouvrir » la recherche de créneau actuelle (celle coté agent) à toutes les organisations ?

**Comment by yaf** [comment]
> bonjour ,
> merci pour votre retour, quand je lis la proposition il me semble que cette condition technique répondrait à notre besoin. seulement en regardant le dispositif nous ne sommes pas du tout dans ce cas de figure puisque nos agents chargés des appels, traite les demandes des usagers non pas pour les aider mais pour prendre rdv sur notre application, c'est un canal en plus. Ne pas savoir qui a pris le rdv pose probléme d'une part et d'autre part d'un point de vue éthique si je puis dire ou même protection des données l'objectif n'est pas du tout d'aider l'usager. Je voulais donc préciser avec vous si l'objectif de s'inspirer de ce dispositif est seulement au sens technique ou de prendre un habilitation "aidant" pour les chargés d'appels du CD92? je vous remercie

-- Marianne (92)

**Comment by yaf** [comment]
J'avais en tête la possibilité que ce soit une habilitation. Merci de votre rapide réponse, ça nous permet d'écarter cette possibilité.


La recherche de créneau inter-organisation pour un usager correspond bien à une piste. J'ai l'impression, dans ce cadre, que le plus facile serait donc de « déverrouiller » la recherche de créneau pour pouvoir la faire sur plusieurs organisations.
Ceci étant, pour les départements où il y a un cloisonnement par organisation, il faudrait pouvoir bloquer cette possibilité.

D'autres pistes ?

**Comment by yaf** [comment]
> Je partage en effet la piste que tu évoques @Yannick je pense qu'il faudrait ouvrir une nouvelle interface de recherche de créneaux côté agents mais inter-organisations.  
> 
> L'introduction de l'entité "départements" qui est en cours devrait faciliter ça. Cependant cela pose la question de l'appartenance d'un usager à une organisation, mais ce n'est pas nécessairement bloquant. Si les secrétaires en question appartiennent bien aux 13 orgas du département, i.e.lles peuvent voir tous les usagers du département. Il n'y a donc qu'un pas à dire qu'un usager existant d'une orga 1 peut chercher un créneau dans une orga 2 - c'est déjà le cas depuis la recherche côté usager, il faudrait rajouter ça côté agent. 
> 
> Il faudrait réfléchir un peu à comment et où se présenterait cette nouvelle recherche de créneaux inter-organsiations : est-ce une nouvelle interface ou bien générise-t-on l'interface existante?

-- Adrien

**Comment by francois-ferrandis** [comment]
La fonctionnalité évoquée ici est plus ou moins ce que nous appelons désormais la "prescription agent", implémentée ici : https://github.com/betagouv/rdv-service-public/pull/3942
