### ISSUE TITLE
Extraction de la liste des agents 

### ISSUE THREAD

**Issue by MYRIAMKEDDAD** [betagouv/rdv-service-public#2972]
Actuellement les lettres d'informations sont envoyées par mail aux référentes.

Nous souhaiterions l'envoyer par l'intermédiaire de sendinblue  à tous les agents des départements suivants  le 62 , le 55, le 14, le 22. 
Comportement attendu : pouvoir exporter la liste des agents d’un département pour l’importer dans SendInBlue

**Comment by yaf** [comment]
Je mets un tag configuration parce que nous pourrions envisager d'ajouter un bouton d'export de la liste des agents dans la page du module de configuration.

![Screenshot 2022-11-03 at 11-15-43 RDV Solidarités](https://user-images.githubusercontent.com/42057/199695749-fdc974c3-bb40-4901-b6e6-5c953e80127f.png)
