### ISSUE TITLE
Mauvaises couleurs de plages d'ouverture dans l'agenda pour un agent multiorganisation

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-service-public#3193]
ref : https://zammad10.ethibox.fr/#ticket/zoom/3621

## Actuellement

En production seulement ;
Lorsqu'un agent est sur deux organisations ;
Avec des plages d'ouvertures sur les deux (A et B);
L'affichage de l'agenda de l'agent sur une des organisations affiche bien la plage d'ouverture A en bleu ciel et la B en gris ;
Lorsque l'agent bascule sur l'autre organisation et affiche son agenda, la plage d'ouverture A reste en bleu ciel et la B en gris (alors que ça devrait s'inverser)

## Objectif

Explorer le problème qui semble venir d'une gestion de cache.

Une autre option, plus complexe sans doute, consisterait à amorcer la suppression du scope par organisation dans le module métier.

**Comment by francois-ferrandis** [comment]
Fixed in #3833
