### ISSUE TITLE
En tant qu’agent, je vois une demande d’invitation pour mon compte qui est déjà activé

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-service-public#3335]
**Contexte de reproduction :** 
Un agent (id : 13559) utilise son compte RDV Solidarité : des RDV sont pris, les plages d'ouvertures établies, les agents invités... Bien que l'agent utilise son compte, le compte de l'agent se comporte comme un compte n'ayant pas été activé :
- sur superadmin le bouton "Inviter" (capture n°1) apparait. 
- sur le compte de l'agent dans Paramètres > agent ou invitation : l'agent qui est connecté sur son voit "Renvoyer l'invitation" à côté de son nom / prénom (capture n°2)

Capture n°1 : 
![](https://user-images.githubusercontent.com/103633345/217565589-33701b2d-3bb8-4ea6-838b-f82bf4aa4166.png)

Capture n°2 : 
![Image](https://user-images.githubusercontent.com/103633345/217802826-51247c79-6f5d-4ab0-9192-e5da874182f7.png)

**Comment by NesserineZarouri** [comment]
**Définition du problème** 
Un agent (id : 13559) utilise son compte RDV Solidarité : des RDV sont pris, les plages d'ouvertures établies, les agents invités... Bien que l'agent utilise son compte, sur superadmin le bouton "Inviter" (capture n°1) apparait. Aussi sur le compte de l'agent, lorsqu'il se rend sur : 
- Paramètres > agent ou invitation : l'agent qui est connecté sur son voit "Renvoyer l'invitation" à côté de son nom / prénom (capture n°2) 

Capture n°1 : 

![Image](https://user-images.githubusercontent.com/103633345/217565589-33701b2d-3bb8-4ea6-838b-f82bf4aa4166.png)


Capture n°2 : 


![Image](https://user-images.githubusercontent.com/103633345/217565633-2364f790-ecd0-4bc1-9ab2-2a44fb0dddcc.png)

**Comment by mekaidmekaid** [comment]
@NesserineZarouri toujours d'actualité ?

**Comment by NesserineZarouri** [comment]
Non c'est plus le cas
