### ISSUE TITLE
Pouvoir se connecter en super_admin (en tant qu'un agent) sur rdv-aide-numerique

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-service-public#3366]
Demande du support. @NesserineZarouri 
Je dois pouvoir accéder à l'interface super admin afin de pouvoir me connecter "en tant qu'agent" pour reproduire le problème remonté par l'agent sur l'interface de **rdv-aide-numerique**.

Omniauth est configuré pour le domaine rdv-solidarites.
A creuser techniquement.

**Comment by mekaidmekaid** [comment]
@NesserineZarouri @Holist est ce toujours d'actualité ?

**Comment by francois-ferrandis** [comment]
Je viens de tester et ça a été corrigé, visiblement. :wink:
