### ISSUE TITLE
Feature: Changer le service d'un agent

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-service-public#3440]
## Actuellement

Une validation empêche de changer le service d'un agent. Cette contrainte a été ajoutée il y a deux ans dans #992. 

La PR pointe vers [un ticket Trello expliquant la raison de la contrainte](https://trello.com/c/c3ycMAQT/1144-emp%C3%AAcher-le-changement-de-service-dun-agent-pour-%C3%A9viter-les-incoh%C3%A9rences) : 

> ### Problème
> 
> reproduction :
> - créer un agent en PMI
> - créer une Plage d'Ouverture avec des motifs de la PMI pour cet agent
> - changer de service vers secrétariat
> - chercher un créneau pour cet agent, on voit ses plages d'ouvertures mais lorsqu'on avance l'agent n'est plus sélectionnable pour créer ce RDV
> 
> ### solution
> 
> empêcher le changement de service

## Objectif

Nous avons régulièrement des demandes au support pour changer le service d'un agent (la plupart du temps passer de "Secrétariat" à un autre service, ou inversement). 

Exemple : https://zammad10.ethibox.fr/#ticket/zoom/4874

L'objectif est de permettre soit à un agent (référente) soit au support (super admin) de changer le service, dans le cas où l'agent n'ait pas de plage d'ouverture.

**Comment by victormours** [comment]
Voir aussi le ticket zammad https://zammad10.ethibox.fr/#ticket/zoom/6510, qui argumente pour qu'on puisse avoir plusieurs services par agent

**Comment by francois-ferrandis** [comment]
Fixed in #3846
