### ISSUE TITLE
Customiser nos pages d'erreur (404 et 500)

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-service-public#3536]
## ℹ️ Contexte 

Actuellement nos pages d'erreur sont statiques, et donc **elles affichent toutes le branding RDV Solidarités** :

https://www.rdv-mairie.fr/500.html

![image](https://github.com/betagouv/rdv-solidarites.fr/assets/6357692/eed7e565-0010-43be-b803-06a5aa74710c)

https://www.rdv-mairie.fr/404.html

![image](https://github.com/betagouv/rdv-solidarites.fr/assets/6357692/40d79cd4-8fbc-453f-ab41-a5d7a49427c7)

## ❓ Définition du problème

Cela crée de la confusion pour les agents et usagers des autres domaines

## 💡 Solution envisagée

- Avoir un branding différent selon le domaine
- ou avoir des pages génériques "RDV Service Public" (mais sans bouton "Retour à l'accueil" :worried: )

**Comment by victormours** [comment]
Notre ami Adrien di Pasquale a bossé là dessus récemment pour Collectif Objets, on pourrait reprendre ce qu'il a fait (en plus c'est une intégration intéressante du dsfr)

**Comment by francois-ferrandis** [comment]
Fixed in #4480
