### ISSUE TITLE
API de doublons ANTS pas mise à jour quand on change les participants d'un rdv

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-service-public#3669]
En tant qu'agent : Si je change les participants d'un rdv en enlevant un participant et en mettant un autre, le nouveau est bien mis à jour sur l'api de l'ants, mais pas l’ancien (et il y a ensuite une erreur quand on crée un rdv avec le numéro de pré-demande du participant qui est supprimé). (Il faut faire la modif en un seul coup)

**Comment by adipasquale** [comment]
il me semble que ce souci a été corrigé avec #4734
