### ISSUE TITLE
Erreur sur les numéro de pré-demande ANTS invalides côté prescripteur

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-service-public#3703]
Un usager avec un numéro de pré-demande invalide côté prescripteur lève une erreur 500 plutôt qu’une erreur de validation.
voir https://sentry.incubateur.net/organizations/betagouv/issues/56095/?environment=production&query=is%3Aunresolved&referrer=issue-stream

--- 

Auteur : Adrien 

Le job `Ants::SyncAppointmentJob` lève des `AntsApi::ApiRequestError` en grande quantité : 1600 sur 30 jours.

Le message renvoyé par l’API ANTS ressemble à ça : 

```
code:422, body:{"detail":[{"loc":["query","application_ids",0],"msg":"string does not match regex \"^([A-Z0-9]{10}[,;:\\-/.\\s])*[A-Z0-9]{10}$\"","type":"value_error.str.regex","ctx":{"pattern":"^([A-Z0-9]{10}[,;:\\-/.\\s])*[A-Z0-9]{10}$"}}]} (AntsApi::ApiRequestError)
```

Si je comprends bien le pattern attendu pour les application IDS est :

`[10 chiffres ou lettres][un séparateur éventuel][10 chiffres ou lettres]`

Pistes d’explication :

1. Notre validation de IDs ANTS n’est pas correcte `/\A[A-Z0-9]{10}\z/` cf [User::Ants](https://github.com/betagouv/rdv-service-public/blob/production/app/models/concerns/user/ants.rb/#L9)
2. On fait des requêtes API pour des valeurs d’IDs ANTS déjà anonymisées
3. Le problème vient des requêtes pour des IDs "obsolètes" qui sont invalides

La piste 3 semble l’explication la plus probable. 
Quand on regarde les arguments des jobs en erreur on voit beaucoup de ces IDs obsolètes avec des valeurs qui ne collent pas du tout à la regex : `EDOUAR`, `1159-3842`, `U4FZW2G2U` ...

Pistes de solutions :

Je n’ai pas assez d’informations sur ces obsolete ids pour savoir ce qu’il faut faire. 
@ousmanedev j’ai l’impression que tu as pas mal investigué ce sujet, est-ce que tu pourrais compléter avec tes observations quand tu as le temps ?

**Comment by adipasquale** [comment]
@victormours je ne suis pas 100% sûr que ce soit le même cas mais j’ai lié ce ticket GH à [cette issue Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/93299) car ça me semble similaire et que ton lien vers Sentry ne fonctionne plus 🤷 

Edit:
maintenant que j’ai rédigé tout ça et modifié la description plus haut je crois comprendre que ce n’était pas du tout le même cas que tu signalais. Je pense qu’il faut que j’extrais mes infos dans un autre ticket GH, qu’en penses tu?

**Comment by francois-ferrandis** [comment]
J'avais un peu creusé : on a bien des IDs qui ne respectent pas la regexp.

On peut les retrouver comme ça : 

```ruby
User
  .where("ants_pre_demande_number IS NOT NULL")
  .where.not("ants_pre_demande_number ~ '^[A-Z0-9]{10}$'")
  .limit(100)
  .pluck(:ants_pre_demande_number, :created_at)
```

Beaucoup ont un espace à la fin ou un espace au début, ou sont du genre `"      "`. 

**Ma piste : on dirait que ce sont tous des proches (des enfants), c'est donc vraisemblablement le formulaire d'ajout de proche qui ne fait pas la vérif `validate_ants_pre_demande_number`.**

**Comment by adipasquale** [comment]
je ferme cette issue en faveur de #4777 car je crois que ça recouvre exactement ce problème maintenant qu’on l’a bien identifié et qualifié
