### ISSUE TITLE
Récupérer certain  RDV du 92 et les basculer vers une nouvelle organisation

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-service-public#3705]
https://zammad10.ethibox.fr/#ticket/zoom/6510

> Bonjour,
> 
>  
> 
> Afin de mieux nous conformer au RGPD, nous envisageons de créer une nouvelle organisation qui regrouperait l’ensemble des professionnels, motifs et RDV relatifs à la mission Centre de santé sexuelle. A ce jour, ces données sont réparties sur 13 organisations, correspondant à notre découpage territorial.
> 
>  
> 
> Il nous serait nécessaire que les RDV jusqu’à présent créés sur ces 13 organisations, correspondant à 10 motifs (pour l’activité Centre de santé sexuelle) puissent être requêtés et modifiés afin d’être retrouvés, avec les usagers participants à ces RDV, afin d’appartenir à cette future nouvelle organisation.
> 
>  
> 
> Cette nouvelle organisation n’est pas encore créée, car nous devons obtenir la validation du métier avant sa mise en place en production. Avant cela, nous devons présenter les avantages et les inconvénients. C’est pour cela que je vous sollicite afin que vous puissiez m’indiquer la faisabilité de cette demande.
> 
>  
> 
> J’espère avoir été claire dans l’expression de notre besoin.
> 
>  
> 
> Bonne fin de journée,

**Comment by francois-ferrandis** [comment]
J'ai répondu sur le Zammad pour donner une idée des complications possibles de cette migration, et demander si le besoin est toujours avéré.

**Comment by mekaidmekaid** [comment]
Je passe en done, outcome atteint sur https://github.com/betagouv/rdv-service-public/pull/3846
