### ISSUE TITLE
Refonte de la vue "journée" dans agenda

### ISSUE THREAD

**Issue by Teodora-Stanki** [betagouv/rdv-service-public#3728]
Problème : La vue "journée" de l'agenda mobilise beaucoup trop d'espace (peur importe les resolutions) pour pas plus d'informations disposées.

![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/129159292/eecf19a6-2311-4b30-8cf2-516a489fa1f8)

Solution possible : Spliter l'espace en deux, pour proposer à gauche le planning de la journée et a droite un focus sur chaque rdv avec possibilité de modifier sans passer par le tunnel de modification de rdv.

**Comment by mekaidmekaid** [comment]
Sera traité dans un ticket d'amélioration de la liste des RDV.
