### ISSUE TITLE
Afficher les relations dans le super_admin plutôt que les models cibles

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-service-public#3788]
## ℹ️ Contexte 

Suite à https://github.com/betagouv/rdv-solidarites.fr/pull/3778
J'ai remarqué un problème d'interface qui me semble plutôt gênant dans le super_admin.

## ❓ Définition du problème

Quand on est sur un model qui a des associations, ex : un agent qui a plusieurs organisations, dans la show on affiche les organisations dont il est membre avec les boutons Modifier/Supprimer, hors ces boutons portent à confusion, ils ne servent pas à supprimer la relation mais directement l'objet (l'organisation dans notre exemple). 
Pour supprimer la relation avec l'organisation il faut supprimer le rôle lié à l'organisation.
C'est un exemple parmi d'autres car un problème similaire se pose aussi pour les motifs et les service. (`has_many` et `belongs_to`)

![Capture d’écran 2023-09-20 à 11 36 05](https://github.com/betagouv/rdv-solidarites.fr/assets/28594222/075d66a8-9ad1-4532-9a3b-639ffa24d496)

![Capture d’écran 2023-09-20 à 11 44 52](https://github.com/betagouv/rdv-solidarites.fr/assets/28594222/22797094-26de-495a-8115-045ddc21c629)

## 💡 Solution envisagée

Revoir la manière dont les associations sont affichées dans les show pour les différents models.
Afficher les relations plutôt que les models cibles ou ne pas afficher les boutons modifier/supprimer dans les show.
Mettre en place des traductions précises pour améliorer la compréhension de l'interface super_admin.
Lié à https://github.com/betagouv/rdv-solidarites.fr/issues/3622 qui envisage une refonte un peu plus complète du super_admin avec la mise en place de droits plus restreints.

**Comment by francois-ferrandis** [comment]
Un exemple de besoin en rapport avec ça est signalé ici : #3912
