### ISSUE TITLE
Il me semble que c'est plutôt le champ `current_sign_in_at` qu'il faut mettre à jour ici

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/rdv-service-public#3837]
https://github.com/betagouv/rdv-solidarites.fr/blob/53b4703cf11c04a374c792840845bfffd83d440a/app/services/inclusion_connect.rb#L72C16-L72C16

En fait, j'aurai plutôt écrit : 

```
       agent.update!(
        current_sign_in_at: Time.zone.now,
        last_sign_in_at: agent.current_sign_in_at,
        sign_in_count: agent.sign_in_count + 1
      )
```

**Comment by francois-ferrandis** [comment]
Merci Étienne ! Ces colonnes sont en train d'être supprimées, merci d'avoir soulevé notre attention sur ce sujet !
