### ISSUE TITLE
Supprimer colonnes inutilisés dans la base

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-service-public#3838]
Il semblerait que ces champs soient inutilisés, on peut les virer pour plus de lisibilité :

- `legacy_bookable_publicly`
- `old_location_type`
- `old_enabled`
- `old_address`
- `old_location_type`
- `old_location`

**Comment by victormours** [comment]
Les colonnes `agents.provider` et `agents.uid` pourraient être remplacées par les méthodes suivantes :
```
def provider
  "email"
end

def uid
  email
end
```
Ça amènerait aussi à des simplifications de `app/models/concerns/agent/custom_devise_token_auth_user_omniauth_callbacks.rb`

Il faudra aussi creuser `agents.allow_password_change` qui peut sans doute être simplifié de la même manière
